### ISSUE TITLE
Unable to delete items and folders with bitwarden-web v1.24.0

### ISSUE THREAD

**Issue by leonghui** [VictorNine/bitwarden-go#27]
Deleting an existing item appears to work but upon refresh, the item still exists. Same behaviour when deleting folders.

Server stdout reports:
`2018/03/24 04:32:25 user@user.com is trying to edit his data`
`2018/03/24 04:32:25 strconv.ParseInt: parsing   "67/delete": invalid syntax`
...
`2018/03/24 04:37:57   user@user.com is trying to update a folder`
`2018/03/24 04:37:57   Folder 423b3f90-46ee-448d-adb0-a9f47edcef89/delete updated`

Deletion works fine for other bitwarden clients (e.g. Android app, Firefox extension).

**Comment by Odysseus16** [comment]
I have also implemented the new API. So if you want, you can try my version (but at the moment the database is not compatible with VictorNines.
I plan to submit a pull request in the next time, but as I have done major changes it is hard to make my branch compatible with VictorNines.

**Comment by leonghui** [comment]
@Odysseus16 
Thanks for your work, I am looking forward to Totp support but I will need to migrate my data over to your build for testing.

@VictorNine 
Issue above still exists after https://github.com/VictorNine/bitwarden-go/commit/17c1ff32c9b7f79af870ce8295cb6f5ee9b4bb16 (tested: Android app 1.51.2, Firefox extension 1.25.7, and bitwarden-web 1.25.1)

**Comment by timreuscher** [comment]
@Odysseus16 Does your fork support Match Detection yet? I know this one doesn’t.

**Comment by VictorNine** [comment]
Have you tried after the latest commit? Should be working

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by timreuscher** [comment]
@VictorNine My bad. It does work after the update. I just made the change in the web vault but hasn’t synced it to my browser add-on. Appreciate the work on this.

**Comment by VictorNine** [comment]
Good to hear. I'll look in to the folders as well

**Comment by davehope** [comment]
@victornine, did you ever get to look at the folder deletion issue?
